spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: cliente-service-link
          uri: lb://cliente-service
          predicates:
            - Path=/clientes/**
        - id: cartao-service-link
          uri: lb://cartao-service
          predicates:
            - Path=/cartoes/**
        - id: avaliador-credito-service-link
          uri: lb://avaliador-credito-service
          predicates:
            - Path=/avaliacoes-credito/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://localhost:8081/realms/ms-rabbitmq-realm

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://ms-eureka-server:err-vremss-keaue@localhost:8761/eureka
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log
  level:
    root: info