spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: cliente-service-link
          uri: lb://cliente-service
          predicates:
            - Path=/clientes/**
        - id: cartao-service-link
          uri: lb://cartao-service
          predicates:
            - Path=/cartoes/**
        - id: avaliador-credito-service-link
          uri: lb://avaliador-credito-service
          predicates:
            - Path=/avaliacoes-credito/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true