spring:
  application:
    name: eureka-server
  security:
    user:
      name: ms-eureka-server
      password: err-vremss-keaue

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false